
tasks:
  # - init: | # runs during prebuild
  #     sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl
  #     curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
  #     sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
  #     sudo apt-get update && sudo apt-get install terraform
      
    - command: | # Seems like gitpod has a bug so we just install here
        sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        sudo apt-get update && sudo apt-get install terraform
        sudo apt-get update
        sudo apt-get install python3
        cd infrastructure && terraform init

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
# ports:
#   - port: 3000
#     onOpen: open-preview
vscode:
  extensions:
    - ms-toolsai.jupyter
    - ms-python.python
