
name: 'Benchmark - Output'

on:
  workflow_dispatch:
    # inputs:
    #   logLevel:
    #     description: 'Log level'     
    #     required: true
    #     default: 'warning'
    #   tags:
    #     description: 'Test scenario tags'  

jobs:
  terraform:
    name: 'Test'
    runs-on: ubuntu-latest
    timeout-minutes:  240
    defaults:
      run:
        shell: bash

    steps:
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: "dspj-315716"
        service_account_key: ${{ secrets.GCE_CREDENTIALS }}
        export_default_credentials: true

    - name: Create directory
      run: mkdir /tmp/logoutput

    - name: Use gcloud CLI
      run: gcloud compute instances get-serial-port-output  experiment-baseline-with-latency-3-test-orchestrator > /tmp/logoutput/test.log

    - name: cat
      run: cat /tmp/logoutput/test.log 
